<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClientOauthTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $users_count = DB::table('oauth_clients')->count();

        DB::table('oauth_clients')->delete();
        DB::table('oauth_personal_access_clients')->delete();

        if($users_count == 0){
            DB::table('oauth_clients')->delete();

            DB::table('oauth_clients')->insert([
                'id' => 1,
                'name' => 'B2a Access Client',
                'secret' => 'ucGfcnkb5aTXMS3fcJEiAZlSp4KGKGahBZIgf2ro',
                'redirect' => env('APP_URL'),
                'personal_access_client' => 1,
                'password_client' => 0,
                'revoked' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ]);

            DB::table('oauth_clients')->insert([
                'id' => 2,
                'name' => 'B2a Personal Access Client',
                'secret' => 'NRCx71HwSJ0VCNCgRkw8wVI73vSmCwyWEIsb0qLG',
                'redirect' => env('APP_URL'),
                'personal_access_client' => 0,
                'password_client' => 1,
                'revoked' => 0,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ]);

            DB::table('oauth_personal_access_clients')->insert([
                'id' => 1,
                'client_id' => 1,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s')
            ]);
        }

       /* DB::raw("INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'BIOHULIN® 70/30', 'SUSPENSÃO INJETÁVEL REFIL 5 X 1,5 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'BIOHULIN® 70/30', 'SUSPENSÃO INJETÁVEL REFIL 5 X 3 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'BIOHULIN® 70/30', 'SUSPENSÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'BIOHULIN® 80/20', 'SUSPENSÃO INJETÁVEL REFIL 5 X 1,5 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'BIOHULIN® 80/20', 'SUSPENSÃO INJETÁVEL REFIL 5 X 3 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'BIOHULIN® 80/20', 'SUSPENSÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'BIOHULIN® 90/10', 'SUSPENSÃO INJETÁVEL REFIL 5 X 1,5 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'BIOHULIN® 90/10', 'SUSPENSÃO INJETÁVEL REFIL 5 X 3 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'BIOHULIN® 90/10', 'SUSPENSÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'ACTRAPID® MC', 'SOLUÇÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'BIOHULIN® GERAL', 'TODAS', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'BIOHULIN® L', 'SUSPENSÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'BIOHULIN® N', 'SUSPENSÃO INJETÁVEL REFIL 5 X 1,5 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'BIOHULIN® N', 'SUSPENSÃO INJETÁVEL REFIL 5 X 3 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'BIOHULIN® N', 'SUSPENSÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'BIOHULIN® R', 'SOLUÇÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'BIOHULIN® R', 'SOLUÇÃO INJETÁVEL REFIL 5 X 1,5 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'BIOHULIN® R', 'SOLUÇÃO INJETÁVEL REFIL 5 X 3 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'BIOHULIN® ULTRALENTA', 'SUSPENSÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'CLORIDRATO DE METFORMINA 500 MG', 'CAIXA COM 3 BLISTERS DE 10 COMPRIMIDOS', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'CLORIDRATO DE METFORMINA 850 MG', 'CAIXA COM 3 BLISTERS DE 10 COMPRIMIDOS', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'DEVICES GERAL', 'TODAS', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'DIABETES GERAL', 'TODAS', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'GLUCAGEN® HYPOKIT', 'KIT FRASCO DE 1 MG (1 UI) PÓ LIOFILIZADO + FRASCO DE DILUENT', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'GLUCOFORMIN® 500 MG', 'CAIXA COM 3 BLISTERS DE 10 COMPRIMIDOS', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'GLUCOFORMIN® 850 MG', 'CAIXA COM 3 BLISTERS DE 10 COMPRIMIDOS', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'GLUCOFORMIN® GERAL', 'TODAS', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'INNOVO®', 'CAIXA COM 1 SISTEMA DE APLICAÇÃO', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'INSULINAS GERAL', 'TODAS', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'IOLIN® GERAL', 'TODAS', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'IOLIN® N', 'SUSPENSÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'IOLIN® R', 'SOLUÇÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'LEVEMIR FLEXPEN', 'SOLUÇÃO INJETÁVEL SISTEMA DESCARTÁVEL 5 X 3 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'LEVEMIR FLEXPEN - SINGLE PACK', 'SOLUÇÃO INJETÁVEL SISTEMA DESCARTÁVEL 1 X 3 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'LEVEMIR GERAL', 'TODAS', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'LEVEMIR PENFILL®', 'SOLUÇÃO INJETÁVEL PENFILL 5 X 3 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'MONOLIN® N', 'SUSPENSÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'MONOLIN® R', 'SOLUÇÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'MONOTARD® MC', 'SUSPENSÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NEOSULIN® GERAL', 'TODAS', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NEOSULIN® L', 'SUSPENSÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NEOSULIN® N', 'SUSPENSÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NEOSULIN® R', 'SOLUÇÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOLIN® N', 'SUSPENSÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOLIN® 70/30', 'SUSPENSÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOLIN® 70/30 PENFILL®', 'SUSPENSÃO INJETÁVEL PENFILL 5 X 3 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOLIN® 80/20 PENFILL®', 'SUSPENSÃO INJETÁVEL PENFILL 5 X 3 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOLIN® 90/10 PENFILL®', 'SUSPENSÃO INJETÁVEL PENFILL 5 X 3 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOLIN® GERAL', 'TODAS', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOLIN® L', 'SUSPENSÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOLIN® N - MINISTÉRIO DA SAÚDE', 'SUSPENSÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOLIN® N PENFILL®', 'SUSPENSÃO INJETÁVEL PENFILL 5 X 3 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOLIN® R', 'SOLUÇÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOLIN® R - MINISTÉRIO DA SAÚDE', 'SOLUÇÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOLIN® R PENFILL®', 'SOLUÇÃO INJETÁVEL PENFILL 5 X 3 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOLIN® U', 'SUSPENSÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOMIX® 30 FLEXPEN', 'SUSPENSÃO INJETÁVEL SISTEMA DESCARTÁVEL 5 X 3 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOMIX® 30 GERAL', 'TODAS', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOMIX 30 PENFILL®', 'SUSPENSÃO INJETÁVEL PENFILL 5 X 3 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVONORM® 0,5 MG', 'CAIXA COM 2 BLISTERS DE 15 COMPRIMIDOS BRANCOS', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVONORM® 1 MG', 'CAIXA COM 2 BLISTERS DE 15 COMPRIMIDOS AMARELOS', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVONORM® 2 MG', 'CAIXA COM 2 BLISTERS DE 15 COMPRIMIDOS VERMELHOS', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVONORM® GERAL', 'TODAS', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVORAPID®', 'SOLUÇÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVORAPID® FLEXPEN', 'SOLUÇÃO INJETÁVEL SISTEMA DESCARTÁVEL 5 X 3 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVORAPID® FLEXPEN - 3 ML - SINGLE PACK', 'SOLUÇÃO INJETÁVEL SISTEMA DESCARTÁVEL 1 X 3 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVORAPID® GERAL', 'TODAS', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVORAPID® PENFILL®', 'SOLUÇÃO INJETÁVEL PENFILL 5 X 3 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'PROTAPHANE® MC', 'SOLUÇÃO INJETÁVEL FRASCO 10 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'TRESIBA GERAL', 'TODAS', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'TRESIBA FLEXTOUCH', 'SOLUÇÃO INJETÁVEL SISTEMA DESCARTÁVEL 1 X 3 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'TRESIBA PENFILL®', 'SOLUÇÃO INJETÁVEL PENFILL 5 X 3 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU GLP1', '082.277.955/0001-55', '1', '', '', '', 'VICTOZA® 6 MG/ML', 'SOLUÇÃO INJETÁVEL SISTEMA DESCARTÁVEL 2 X 3 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOFINE 32G TIP ETW - 0.25 X 6 MM X 0.23', 'CAIXA COM 100 UNIDADES DE AGULHAS', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOFINE® 28G - 0.36 X 12 MM', 'CAIXA COM 100 UNIDADES DE AGULHAS', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOFINE® 30G - 0.30 X 6 MM', 'CAIXA COM 100 UNIDADES DE AGULHAS', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOFINE® 30G - 0.30 X 8 MM', 'CAIXA COM 100 UNIDADES DE AGULHAS', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOFINE® GERAL', 'TODAS', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOPEN® 3 - AZUL', 'ESTOJO COM 1 SISTEMA DE APLICAÇÃO AZUL', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOPEN® 3 - PRATA', 'ESTOJO COM 1 SISTEMA DE APLICAÇÃO PRATA', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOPEN® 3 - VERDE', 'ESTOJO COM 1 SISTEMA DE APLICAÇÃO VERDE', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOPEN® 3 DEMI', 'ESTOJO COM 1 SISTEMA DE APLICAÇÃO LARANJA E AZUL', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOPEN® 3 PENMATE', 'ESTOJO COM 1 ACESSÓRIO', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOPEN® 4', 'ESTOJO COM 1 SISTEMA DE APLICAÇÃO AZUL', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOPEN® GERAL', 'TODAS', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDIFINE® 30G - 0.3 X 12 MM', 'CAIXA COM 100 UNIDADES DE AGULHAS', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDIFINE® 30G - 0.3 X 8 MM', 'CAIXA COM 100 UNIDADES DE AGULHAS', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDIFLEX PENMATE®', 'ESTOJO COM 1 ACESSÓRIO', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDIPENMATE - CLASSIC', 'ESTOJO COM 1 ACESSÓRIO', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDIPENMATE - GRAPHIC', 'ESTOJO COM 1 ACESSÓRIO', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDIPEN 10 - CLASSIC', 'ESTOJO COM 1 SISTEMA DE APLICAÇÃO', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDIPEN 10 - GRAPHIC', 'ESTOJO COM 1 SISTEMA DE APLICAÇÃO', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDIPEN 15 - CLASSIC', 'ESTOJO COM 1 SISTEMA DE APLICAÇÃO', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDIPEN 15 - GRAPHIC', 'ESTOJO COM 1 SISTEMA DE APLICAÇÃO', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDIPEN 5 - CLASSIC', 'ESTOJO COM 1 SISTEMA DE APLICAÇÃO', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDIPEN 5 - GRAPHIC', 'ESTOJO COM 1 SISTEMA DE APLICAÇÃO', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDIPEN GERAL', 'TODAS', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDITROPIN NORDIFLEX® 10', 'SISTEMA DE APLICAÇÃO DESCARTÁVEL 10 MG X 1,5 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDITROPIN NORDIFLEX® 15', 'SISTEMA DE APLICAÇÃO DESCARTÁVEL 15 MG X 1,5 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDITROPIN NORDIFLEX® 5', 'SISTEMA DE APLICAÇÃO DESCARTÁVEL 5 MG X 1,5 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDITROPIN® 12 UI (4 MG)', 'FRASCO 12 UI DE PÓ LIOFILIZADO + FRASCO 3 ML DE DILUENTE', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDITROPIN® 4 UI (1,3 MG)', 'FRASCO 4 UI DE PÓ LIOFILIZADO + FRASCO 1 ML DE DILUENTE', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDITROPIN® 4 UI (1,3 MG) - MINISTÉRIO DA SAÚDE', 'FRASCO 4 UI DE PÓ LIOFILIZADO + FRASCO 1 ML DE DILUENTE', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDITROPIN® GERAL', 'TODAS', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDITROPIN® NORDILET 10 - MERCADO PÚBLICO', 'SISTEMA DE APLICAÇÃO DESCARTÁVEL 10 MG X 1,5 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDITROPIN® SIMPLEXX 10', 'SOLUÇÃO INJETÁVEL COM 1 CARTUCHO DE 10 MG X 1,5 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDITROPIN® SIMPLEXX 15', 'SOLUÇÃO INJETÁVEL COM 1 CARTUCHO DE 15 MG X 1,5 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NORDITROPIN® SIMPLEXX 5', 'SOLUÇÃO INJETÁVEL COM 1 CARTUCHO DE 5 MG X 1,5 ML', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NOVOSEVEN® 120', 'FRASCO 2,4 MG PÓ LIOFILIZADO + FRASCO 4,3 ML DILUENTE', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NOVOSEVEN® 120 - MINISTÉRIO DA SAÚDE', 'FRASCO 2,4 MG PÓ LIOFILIZADO + FRASCO 4,3 ML DILUENTE', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NOVOSEVEN® 1MG (50KUI)', 'FRASCO 1 MG PÓ LIOFILIZADO + FRASCO 1,1 ML DILUENTE', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NOVOSEVEN® 1MG (50KUI) - MINISTÉRIO DA SAÚDE', 'FRASCO 1 MG PÓ LIOFILIZADO + FRASCO 1,1 ML DILUENTE', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NOVOSEVEN® 240', 'FRASCO 4,8 MG PÓ LIOFILIZADO + FRASCO 8,5 ML DILUENTE', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NOVOSEVEN® 240 - MINISTÉRIO DA SAÚDE', 'FRASCO 4,8 MG PÓ LIOFILIZADO + FRASCO 8,5 ML DILUENTE', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NOVOSEVEN® 2MG (100KUI)', 'FRASCO 2 MG PÓ LIOFILIZADO + FRASCO 2,1 ML DILUENTE', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NOVOSEVEN® 2MG (100KUI) - MINISTÉRIO DA SAÚDE', 'FRASCO 2 MG PÓ LIOFILIZADO + FRASCO 2,1 ML DILUENTE', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NOVOSEVEN® 5MG (250KUI)', 'FRASCO 5 MG PÓ LIOFILIZADO + FRASCO 5,2 ML DILUENTE', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NOVOSEVEN® 5MG (250KUI) - MINISTÉRIO DA SAÚDE', 'FRASCO 5 MG PÓ LIOFILIZADO + FRASCO 5,2 ML DILUENTE', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NOVOSEVEN® 60', 'FRASCO 1,2 MG PÓ LIOFILIZADO + FRASCO 2,2 ML DILUENTE', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NOVOSEVEN® 60 - MINISTÉRIO DA SAÚDE', 'FRASCO 1,2 MG PÓ LIOFILIZADO + FRASCO 2,2 ML DILUENTE', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU BIOFARMA', '082.277.955/0001-55', '1', '', '', '', 'NOVOSEVEN® GERAL', 'TODAS', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'REPOSIÇÃO HORMONAL - EUROFARMA', '082.277.955/0001-55', '1', '', '', '', 'ACTIVELLE', 'ESTOJO CALENDÁRIO - 28 COMPRIMIDOS', 'Sim', 'Sim', 'Não', '27/02/2015',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'REPOSIÇÃO HORMONAL - MEDLEY', '082.277.955/0001-55', '1', '', '', '', 'ESTROFEM® 1 MG', 'ESTOJO CALENDÁRIO - 28 COMPRIMIDOS', 'Sim', 'Sim', 'Sim', '02/02/2015',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'REPOSIÇÃO HORMONAL - MEDLEY', '082.277.955/0001-55', '1', '', '', '', 'ESTROFEM® 2 MG', 'ESTOJO CALENDÁRIO - 28 COMPRIMIDOS', 'Sim', 'Sim', 'Sim', '02/02/2015',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'REPOSIÇÃO HORMONAL - MEDLEY', '082.277.955/0001-55', '1', '', '', '', 'KLIOGEST®', 'ESTOJO CALENDÁRIO - 28 COMPRIMIDOS', 'Sim', 'Sim', 'Sim', '02/02/2015',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'REPOSIÇÃO HORMONAL - MEDLEY', '082.277.955/0001-55', '1', '', '', '', 'TRISEQUENS® 2 MG', 'ESTOJO CALENDÁRIO - 28 COMPRIMIDOS', 'Sim', 'Sim', 'Sim', '02/02/2015',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'PRANDIN® 0,5 MG', 'CAIXA COM 2 BLISTERS DE 15 COMPRIMIDOS BRANCOS', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'PRANDIN® 1 MG', 'CAIXA COM 2 BLISTERS DE 15 COMPRIMIDOS AMARELOS', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'PRANDIN® 2 MG', 'CAIXA COM 2 BLISTERS DE 15 COMPRIMIDOS VERMELHOS', 'Sim', 'Sim', 'Sim', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'NOVO NORDISK', '082.277.955/0001-55', '1', '', '', '', 'EMPRESA', 'INSTITUCIONAL', 'Sim', 'Sim', 'Não', '14/01/2015',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'NOVO NORDISK', '082.277.955/0001-55', '1', '', '', '', 'MARKETING', 'INSTITUCIONAL', 'Sim', 'Sim', 'Não', '14/01/2015',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'NOVO NORDISK', '082.277.955/0001-55', '1', '', '', '', 'EUROFARMA', 'INSTITUCIONAL', 'Sim', 'Sim', 'Não', '14/01/2015',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'NOVO NORDISK', '082.277.955/0001-55', '1', '', '', '', 'INSTITUCIONAL', 'P & O', 'Sim', 'Sim', 'Não', '02/02/2015',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'NOVO NORDISK', '082.277.955/0001-55', '1', '', '', '', 'INSTITUCIONAL', 'SIC', 'Sim', 'Sim', 'Não', '02/02/2015',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'NOVO NORDISK', '082.277.955/0001-55', '1', '', '', '', 'INSTITUCIONAL', 'AFILIADAS', 'Sim', 'Sim', 'Não', '02/02/2015',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'NOVO NORDISK', '082.277.955/0001-55', '1', '', '', '', 'INSTITUCIONAL', 'CALL CENTER', 'Sim', 'Sim', 'Não', '02/02/2015',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOPEN ECHO', 'ESTOJO COM 1 SISTEMA DE APLICAÇÃO VERMELHO', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU GLP1', '082.277.955/0001-55', '1', '', '', '', 'SAXENDA® 6 MG/ML', 'SOLUÇÃO INJETÁVEL SISTEMA DESCARTÁVEL 3 X 3 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVOFINE 32G TIP ETW - 0.23 X 4 MM X 0.25', 'CAIXA COM 100 UNIDADES DE AGULHAS', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'XULTOPHY®', 'SOLUÇÃO INJETÁVEL SISTEMA DESCARTÁVEL 1 X 3 ML', 'Sim', 'Sim', 'Não', '',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU INSULINAS', '082.277.955/0001-55', '1', '', '', '', 'NOVORAPID® FLEXPEN - MINISTÉRIO DA SÁUDE', 'SOLUÇÃO INJETÁVEL SISTEMA DESCARTÁVEL 5 X 3 ML', 'Sim', 'Sim', 'Não', '24/09/2018',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU GLP1', '082.277.955/0001-55', '1', '', '', '', 'OZEMPIC® 0,25_0,5MG/ML', 'SOLUÇÃO INJETÁVEL SISTEMA DESCARTÁVEL 1 X 1,5 ML/6 AGULHAS', 'Sim', 'Sim', 'Não', '13/02/2019',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU GLP1', '082.277.955/0001-55', '1', '', '', '', 'OZEMPIC® GERAL', 'TODAS', 'Sim', 'Sim', 'Não', '13/02/2019',null,null,null);
            INSERT INTO products (id,active_principle,cnpj,laboratory, ggrem, registry,ean,product,presentation,information,manifestation,discontinued,release_date,code_protheus,created_at,updated_at) VALUES (null,'BU GLP1', '082.277.955/0001-55', '1', '', '', '', 'OZEMPIC® 1 MG/ML', 'SOLUÇÃO INJETÁVEL SISTEMA DESCARTÁVEL 1 X 3 ML/4 AGULHAS', 'Sim', 'Sim', 'Não', '13/02/2019',null,null,null);");
    */}
}
